### ISSUE TITLE
Problem generate sample data

### ISSUE THREAD

**Issue by flavioayres** [IHTSDO/ihtsdo-refset-management-service#1]
Hi,

I am trying to execute step 7 of the tutorial (https://confluence.ihtsdotools.org/display/REFSET/Building+and+Deploying+in+Eclipse) and I am getting the following error:

`[ERROR] Failed to execute goal org.ihtsdo.otf.refset:refset-admin:1.1.4:sample-data (sample) on project refset-admin: Unexpected exception:
 Identifier assignment handler did not properly initialize, serious error. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.ihtsdo.otf.refset:refset-admin:1.1.4:sample-data (sample
) on project refset-admin: Unexpected exception:
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Unexpected exception:
        at org.ihtsdo.otf.refset.mojo.GenerateSampleDataMojo.execute(GenerateSampleDataMojo.java:155)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.Exception: Identifier assignment handler did not properly initialize, serious error.
        at org.ihtsdo.otf.refset.jpa.services.ProjectServiceJpa.<init>(ProjectServiceJpa.java:144)
        at org.ihtsdo.otf.refset.mojo.GenerateSampleDataMojo.execute(GenerateSampleDataMojo.java:120)
        ... 22 more`

Which configuration or URL should I use to make it work?

**Comment by RichardAWood** [comment]
Hello,

Apologies for the delay in responding to you - I've been unavailable for the past few days.  I'm looking into this issue, and will write again within the next 24-48 hours.

In the meantime, if you'd like to contact me directly, please feel free to do so: rwood@westcoastinformatics.com

**Comment by RichardAWood** [comment]
Hello again Flavio,

So after investigating, it turns out your issues come from a couple places.

First, your config.properties is set to IhtsdoComponentIdentifierServceHandler, which requires credentials from SNOMED.  If you don't have these credentials, you can set your config.properties to this instead (I've left the original lines in and commented out, for reference):

#
# Identifier assignment handler - TODO
#
identifier.assignment.handler=DEFAULT
identifier.assignment.handler.DEFAULT.class=org.ihtsdo.otf.refset.jpa.services.handlers.DummyComponentIdentifierServiceHandler
#identifier.assignment.handler.DEFAULT.class=org.ihtsdo.otf.refset.jpa.services.handlers.IhtsdoComponentIdentifierServiceHandler
#identifier.assignment.handler.DEFAULT.url=https://cis.ihtsdotools.org/api
#identifier.assignment.handler.DEFAULT.userName=EDIT_THIS
#identifier.assignment.handler.DEFAULT.password=EDIT_THIS

I also went ahead and ran step 7 of the tutorial myself to make sure, and the version of Snomed referenced needed to be updated as well.  I've made the code updates and pushed them to the master branch - please pull the updates and rebuild.

I hope this works for you, and please let me know if you run into any other problems.

-Rick

**Comment by flavioayres** [comment]
Hi Richard, thanks for the update!

I tried step 7 again and I got the following error:

`Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'admin': was expecting ('true', 'false' or 'null')
 at [Source: admin; line: 1, column: 11]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1486)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2300)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1459)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3600)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3545)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2134)
        at org.ihtsdo.otf.refset.jpa.services.handlers.ImsSecurityServiceHandler.authenticate(ImsSecurityServiceHandler.java:39)
        at org.ihtsdo.otf.refset.jpa.services.SecurityServiceJpa.authenticate(SecurityServiceJpa.java:81)
        at org.ihtsdo.otf.refset.mojo.GenerateSampleDataMojo.execute(GenerateSampleDataMojo.java:130)
        ... 22 more`

In config.properties, I left as it was (prod config):
`#
# URL for security service
#
security.timeout=7200000
security.guest.disabled=false
security.handler=IMS
security.handler.DEFAULT.class=org.ihtsdo.otf.refset.jpa.services.handlers.DefaultSecurityServiceHandler
security.handler.DEFAULT.users.admin=admin
security.handler.DEFAULT.users.viewer=guest,guest1,author1,reviewer1,guest2,author2,reviewer2,guest3,author3,reviewer3,admin1,admin2,admin3
security.handler.IMS.class=org.ihtsdo.otf.refset.jpa.services.handlers.ImsSecurityServiceHandler
security.handler.IMS.url=https://ims.ihtsdotools.org

#
# Admin user for running mojos
#
admin.user=admin
admin.password=admin`

**Comment by RichardAWood** [comment]
Hi again Flavio,

Would you be interested in setting up a Zoom meeting to share screens and get you up and running?  I can see what's causing your current issue, but in case you run into anything else it would be great to be able to help you real-time.

-Rick

**Comment by flavioayres** [comment]
That would be great!

I'll contact you so we can schedule the meeting.

Thanks!

**Comment by RichardAWood** [comment]
Issues was resolved during phone call. The "Building and Deploying in Eclipse" instructions on Confluence are being updated to clarify what needed to be done to get things working.
